# If not set, defaults to the directory name of `source_path`
name: 'AND-GEAR-BEST'

source_path: 'src'

# Sources of metadata
sources:
  nuget: true
  dotnet: true

# Dependencies with these licenses are allowed and will not raise errors or warnings.
# This list does not have a default value and is required for `licensed status`
# to succeed.
allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
