language: csharp  
mono: none  
dotnet: 2.0.0  
dist: trusty 

script:
 - cd src/AndGearbest
 - dotnet restore
 - dotnet build
 
deploy:
  provider: script
  skip_cleanup: true
  script:
    - dotnet pack -c release && dotnet nuget push bin/release/*.nupkg -k $NUGET_API_KEY -s https://www.nuget.org/api/v2/package
  on:
    branch: master
