# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'src/AndGearbest/AndGearbest.csproj'
  buildConfiguration: 'Release'

name: $(majorVersion).$(minorVersion)$(Rev:.r)

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '$(project)'
    configurationToPack: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/AndGearbest/AndGearbest.csproj'
    versioningScheme: 'byBuildNumber'
    verbosityPack: 'Minimal'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
