name: .NET Core

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jonabc/setup-licensed@v1
      with:
        version: '2.x' # required: must satisfy semver.validRange
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/AndGearbest/AndGearbest.csproj
    - name: Build
      run: dotnet build ./src/AndGearbest/AndGearbest.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/AndGearbest/AndGearbest.csproj --no-restore --verbosity normal
    - run: licensed list
